### ISSUE TITLE
Torch built without cuda support

### ISSUE THREAD

**Issue by Fenfel** [JustRin/Stable-Video-Diffusion#1]
For some reason the script uses torch 2.1.0 instead of installing torch 2.0.1. I also updated pip via PowerShell, but the webui.bat console says I have an old version.

webui.bat:

```
[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

```

PowerShell:

```
PS C:\Users\anton> pip install --upgrade pip
Requirement already satisfied: pip in c:\users\anton\appdata\local\programs\python\python310\lib\site-packages (23.3.1)

```
Webui.bat:

```
You can now view your Streamlit app in your browser.

  Local URL: http://localhost:1234
  Network URL: http://192.168.0.107:1234

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.1.0+cpu)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
C:\Games\Stable-Video-Diffusion\venv\lib\site-packages\streamlit\watcher\local_sources_watcher.py:177: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  lambda m: [p for p in m.__path__._path],
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
VideoTransformerBlock is using checkpointing
Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
Initialized embedder #1: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #3: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
Initialized embedder #4: ConcatTimestepEmbedderND with 0 params. Trainable: False
Loading model from checkpoints/svd.safetensors
2023-11-26 17:19:24.961 Uncaught app exception
Traceback (most recent call last):
  File "C:\Games\Stable-Video-Diffusion\venv\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 264, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "C:\Games\Stable-Video-Diffusion\venv\lib\site-packages\streamlit\runtime\caching\cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Games\Stable-Video-Diffusion\venv\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 312, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
  File "C:\Games\Stable-Video-Diffusion\venv\lib\site-packages\streamlit\runtime\caching\cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Games\Stable-Video-Diffusion\venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "C:\Games\Stable-Video-Diffusion\scripts\demo\video_sampling.py", line 120, in <module>
    state = init_st(version_dict, load_filter=True)
  File "C:\Games\Stable-Video-Diffusion\venv\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
  File "C:\Games\Stable-Video-Diffusion\venv\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "C:\Games\Stable-Video-Diffusion\venv\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "C:\Games\Stable-Video-Diffusion\venv\lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "C:\Games\Stable-Video-Diffusion\scripts\demo\streamlit_helpers.py", line 46, in init_st
    model, msg = load_model_from_config(config, ckpt if load_ckpt else None)
  File "C:\Games\Stable-Video-Diffusion\scripts\demo\streamlit_helpers.py", line 115, in load_model_from_config
    model = initial_model_load(model)
  File "C:\Games\Stable-Video-Diffusion\scripts\demo\streamlit_helpers.py", line 74, in initial_model_load
    model.cuda()
  File "C:\Games\Stable-Video-Diffusion\venv\lib\site-packages\lightning_fabric\utilities\device_dtype_mixin.py", line 69, in cuda
    device = torch.device("cuda", torch.cuda.current_device())
  File "C:\Games\Stable-Video-Diffusion\venv\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Games\Stable-Video-Diffusion\venv\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

```

**Comment by JustRin** [comment]
==EN==
Probably one of the libraries produces a newer version, what version of Windows and what video card do you have? I'll look and fix it now.
==Ru==
```Видимо какая-то из библиотек ставит более новую версию, какая версия винды и какая у вас видеокарта? Сейчас посмотю и исправлю.```

**Comment by JustRin** [comment]
Fixed.
